apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: install-{{ item }}
spec:
  istio:
    global:
      imagePullPolicy: Always
      hub: {{ maistra.cr.global.hub }}
      tag: {{ maistra.cr.global.tag }}
      oauthproxy:
        image: {{ maistra.cr.oauthproxy.image }}
        hub:  {{ maistra.cr.oauthproxy.hub }}
    tracing:
      enabled: true
      jaeger:
        hub:  {{ maistra.cr.jaeger.hub }}
        tag:  {{ maistra.cr.jaeger.tag }}
        elasticsearch:
         image: {{ maistra.cr.jaeger.elasticsearch.image }}
         resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "1Gi"
    mixer:
      telemetry:
        autoscaleEnabled: false
        # constrain resources for use in smaller environments
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G
    kiali:
      enabled: true
      hub: {{ maistra.cr.kiali.hub }}
      image: {{ maistra.cr.kiali.image }}
      tag: {{ maistra.cr.kiali.tag }}
  threeScale:
    enabled: true
    hub: {{ maistra.cr.threescale.hub }}
    tag: {{ maistra.cr.threescale.tag }}