- name: "Set auth_strategy to {{ new_auth_strategy }} in current Kiali CR"
  vars:
    current_kiali_cr: "{{ lookup('k8s', api_version='kiali.io/v1alpha1', kind='Kiali', namespace=cr_namespace, resource_name=custom_resource.metadata.name) }}"
  set_fact:
    new_kiali_cr: "{{ current_kiali_cr | combine({'spec': {'auth': {'strategy': new_auth_strategy }}}, recursive=True) }}"

- name: "Change Kiali CR with auth_strategy to {{ new_auth_strategy }}"
  k8s:
    namespace: '{{ cr_namespace }}'
    definition: "{{ new_kiali_cr }}"
