- name: Get Kiali CR if present
  set_fact:
    kiali_cr: "{{ lookup('k8s', api_version='kiali.io/v1alpha1', kind='Kiali', namespace=cr_namespace, resource_name=custom_resource.metadata.name) }}"

- name: Get Kiali Operator Pod
  k8s_facts:
    api_version: v1
    kind: Pod
    namespace: "{{ kiali.operator_namespace }}"
    label_selectors:
    - app = kiali-operator
  register: kiali_operator_pod

- name: Get Kiali Pod
  k8s_facts:
    api_version: v1
    kind: Pod
    namespace: "{{ kiali.install_namespace }}"
    label_selectors:
    - app = kiali
  register: kiali_pod

- name: Get Kiali Configmap
  set_fact:
    kiali_configmap: "{{ lookup('k8s', api_version='v1', kind='ConfigMap', namespace=kiali.install_namespace, resource_name='kiali') }}"

- name: Format Configmap
  set_fact:
    kiali_configmap: "{{ kiali_configmap.data['config.yaml'] | from_yaml }}"

- name: Get Kiali Deployment
  k8s_facts:
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ kiali.install_namespace }}"
    label_selectors:
    - app = kiali
  register: kiali_deployment

- name: Get Kiali Service
  k8s_facts:
    api_version: v1
    kind: Service
    namespace: "{{ kiali.install_namespace }}"
    label_selectors:
    - app = kiali
  register: kiali_service

- name: Get Kiali Route
  k8s_facts:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: "{{ kiali.install_namespace }}"
    label_selectors:
    - app = kiali
  register: kiali_route

- name: Set Kiali's Route URL
  set_fact:
    kiali_base_url: "https://{{ kiali_route.resources[0].spec.host }}"
