---
dependency:
  name: galaxy
platforms:
- name: default
  groups:
  - k8s
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: junit
  playbooks:
    destroy: ../default/destroy.yml
    prepare: ../default/prepare.yml
  inventory:
    group_vars:
      all:
        kiali_operator_assets_path : "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
        cr_file_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/ldap-test/kiali-cr.yaml"
        cr_namespace: kiali-operator
        istio:
          control_plane_namespace: istio-system
        ldap:
          namespace: ldap-test
          deployment_file_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/ldap-test/ldap-deployment.yaml"
          service_file_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/ldap-test/ldap-service.yaml"
          use_ssl: false
        kiali:
          install_namespace: istio-system
          accessible_namespaces: ["**"]
          auth_strategy: ldap
          operator_namespace: kiali-operator
          operator_image_name: quay.io/kiali/kiali-operator
          operator_version: latest
          #operator_image_name: image-registry.openshift-image-registry.svc:5000/kiali/kiali-operator
          #operator_version: dev
          operator_watch_namespace: kiali-operator
          operator_clusterrolebindings: "- clusterrolebindings"
          operator_clusterroles: "- clusterroles"
          image_name: quay.io/kiali/kiali
          image_version: latest
          #image_name: image-registry.openshift-image-registry.svc:5000/kiali/kiali
          #image_version: dev
          image_pull_policy: Always
scenario:
  name: ldap-test
  test_sequence:
  - prepare
  - converge
  - destroy
