- name: Prepare
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: Create Namespaces for Control Planes for OLM
    k8s:
      name: "{{ item }}"
      api_version: v1
      kind: Namespace
      state: present
    with_items:
    - "{{ maistra.cr.control_planes }}"

  - name: Deploy Elasticsearch Subscription
    k8s:
      definition: "{{ lookup('template', elasticsearch_subscription_path) }}"

  - name: Deploy Jaeger Subscription
    k8s:
      definition: "{{ lookup('template', jaeger_subscription_path) }}"

  - name: Deploy Servicemesh Subscription
    k8s:
      definition: "{{ lookup('template', servicemesh_subscription_path) }}"

  - name: Deploy Kiali Subscription
    k8s:
      definition: "{{ lookup('template', kiali_subscription_path) }}"

  - name: Asserting that Kiali Operator is deployed via OLM
    k8s_facts:
      api_version: v1
      kind: Deployment
      namespace: "openshift-operators"
      name: "istio-operator"
    register: operator_deployment
    until: operator_deployment.resources |length == 1 and operator_deployment.resources[0].status.availableReplicas is defined and operator_deployment.resources[0].status.availableReplicas == 1
    retries: 2000
    delay: 10

  - name: Asserting that Maistra Operator is deployed via OLM
    k8s_facts:
      api_version: v1
      kind: Deployment
      namespace: "openshift-operators"
      name: "kiali-operator"
    register: operator_deployment
    until: operator_deployment.resources |length == 1 and operator_deployment.resources[0].status.availableReplicas is defined and operator_deployment.resources[0].status.availableReplicas == 1
    retries: 2000
    delay: 10

  - name: Pause for 2 minutes to wait Maistra to create Admission Controller via OLM
    pause:
      minutes: 2
    
  - name: Deploy Control Planes
    k8s:
      namespace: "{{ item }}"
      definition: "{{ lookup('template', maistra_cr_file_path) }}"
    with_items:
    - "{{ maistra.cr.control_planes }}"

  - name: Asserting that Kialis are Deployed via OLM
    k8s_facts:
      api_version: v1
      kind: Deployment
      namespace: "{{ item }}"
      label_selectors:
      - app = kiali
    register: kiali_deployment
    until: kiali_deployment.resources |length == 1 and kiali_deployment.resources[0].status.availableReplicas is defined and kiali_deployment.resources[0].status.availableReplicas == 1
    retries: 2000
    delay: 10
    with_items:
    - "{{ maistra.cr.control_planes }}"


