---
dependency:
  name: galaxy
platforms:
- name: default
  groups:
  - k8s
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: junit
  inventory:
    group_vars:
      all:
        catalog_sources_file_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/olm-test/assets/catalog-sources.yaml"
        elasticsearch_subscription_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/olm-test/assets/elasticsearch-subscription.yaml"
        jaeger_subscription_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/olm-test/assets/jaeger-subscription.yaml"
        servicemesh_subscription_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/olm-test/assets/servicemesh-subscription.yaml"
        kiali_subscription_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/olm-test/assets/kiali-subscription.yaml"
        maistra_cr_file_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/olm-test/assets/maistra-cr.yaml"
        kiali_test_mesh_operator_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/olm-test/assets/bookinfo"
        
        maistra:
          cr:
            control_planes:
            - "istio-system"
            - "istio-system2"
        kiali:
          test_mesh:             
            operator:
              namespace: kiali-test-mesh-operator
              image: kiali/kiali-test-mesh-operator:latest
            installations:
              - namespace: bookinfo
                control_plane: istio-system
                kind: Bookinfo
                version: 1.14.0
                hub: docker.io/istio
                mongodb: true
                mysql: true
              
              - namespace: bookinfo2
                control_plane: istio-system2
                kind: Bookinfo
                version: 0.12.0
                hub: docker.io/maistra
                mongodb: true
                mysql: false
              
              - namespace: redhat-istio-tutorial
                control_plane: istio-system
                kind: RedHatTutorial
scenario:
  name: olm-test
  test_sequence:
  - create
  - prepare
  - converge
  - destroy
